version: '3.8'

services:
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    env_file:
      - ./.env.docker
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - app-network

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    env_file:
      - ./.env.docker
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
